server:
  port: 5656


spring:
  profiles:
      active: @spring.profiles.active@
  jpa:
      hibernate:
        ddl-auto: validate
      show-sql: true
      properties:
        hibernate:
          dialect: org.hibernate.dialect.MySQL5Dialect
          show_sql: true

  datasource:
      driver-class-name: com.mysql.jdbc.Driver
      tomcat:
        max-wait: 10000
        max-active: 50
        test-on-borrow: true

cibersys:
        services:
          dbm:
            services: /CibersysFirewall/dbm/
            usuario: /CibersysFirewall/dbm/usuario/
            path: CibersysFirewall/dbm/
            route: http://localhost:5656
        token:
              header: X-Auth-Token
              secret: 1234567890*-+/AbCdEfGhIjKlMnOpQrStUvWxYz.,
              expiration: 604800

---
spring:
  profiles: production
  datasource:
    url: jdbc:mysql://localhost:3306/cibersysfirewall?zeroDateTimeBehavior=convertToNull
    username: externos
    password: V45Gty876iuTa99
cibersys:
  services:
      dbm:
        route: http://localhost:5656

---
spring:
  profiles: development
  datasource:
    url: jdbc:mysql://192.168.1.12:3306/CibersysFirewall?zeroDateTimeBehavior=convertToNull
    username: mysql
    password: mysql
cibersys:
  services:
        dbm:
          route: http://localhost:5656

---
spring:
  profiles: remote
  datasource:
    url: jdbc:mysql://aklara.webhop.me:3306/cibersysfirewall?zeroDateTimeBehavior=convertToNull
    username: mysql
    password: mysql
cibersys:
  services:
        dbm:
          route: http://localhost:5656



