server:
  port: 5655

cibersys:
    services:
            login: /CibersysFirewall/public/login
            update: /CibersysFirewall/public/update
            passwordchange: /CibersysFirewall/public/passwordchange
            services:
              public: /CibersysFirewall/public/
              private: /CibersysFirewall/private/
            path: CibersysFirewall/

            dbm:
              services: /CibersysFirewall/dbm/
              usuario: /CibersysFirewall/dbm/usuario
              path: CibersysFirewall/dbm/
              route: http://localhost:5656
            mannager:
              services: /CibersysFirewall/mannager/
              usuario: /CibersysFirewall/mannager/usuario
              update: /CibersysFirewall/mannager/update
              recuperatepassword: /CibersysFirewall/mannager/recuperatepassword
              passwordchange: /CibersysFirewall/mannager/passwordchange

              path: CibersysFirewall/mannager/
              route: http://localhost:5657
  #Configuracion de seguridad
    token:
      header: X-Auth-Token
      secret: 1234567890*-+/AbCdEfGhIjKlMnOpQrStUvWxYz.,
      expiration: 604800


---
spring:
  profiles: production
cibersys:
  services:
            login: /CibersysFirewall/public/login
            update: /CibersysFirewall/public/update
            passwordchange: /CibersysFirewall/public/passwordchange
            services:
              public: /CibersysFirewall/public/
              private: /CibersysFirewall/private/
            path: CibersysFirewall/

            dbm:
              services: /CibersysFirewall/dbm/
              usuario: /CibersysFirewall/dbm/usuario
              path: CibersysFirewall/dbm/
              route: https://localhost:5656
            mannager:
              services: /CibersysFirewall/mannager/
              usuario: /CibersysFirewall/mannager/usuario
              update: /CibersysFirewall/mannager/update
              recuperatepassword: /CibersysFirewall/mannager/recuperatepassword

              path: CibersysFirewall/mannager/
              route: https://localhost:5657

server:
  ssl:
      key-store: /etc/letsencrypt/live/qa.cc.cloudvoice.io/keystore.p12
      key-password: ark123456
      key-store-type: PKCS12
      keyStoreType: PKCS12


  security:
      require-ssl: true

---
spring:
  profiles: development
cibersys:
  services:
        dbm:
          route: http://localhost:5656
        mannager:
          route: http://localhost:5657

---
spring:
  profiles: remote
cibersys:
  services:
        dbm:
          route: http://localhost:5656
        mannager:
          route: http://localhost:5657