server:
  port: 5655

spring:
  profiles:
      active: @spring.profiles.active@

cibersys:
    services:
            path: CibersysFirewall/
            login: /CibersysFirewall/public/login
            update: /CibersysFirewall/public/update
            passwordchange: /CibersysFirewall/public/passwordchange
            services:
              public: /CibersysFirewall/public/
              private: /CibersysFirewall/private/
              path: CibersysFirewall/
            dbm:
              services: /CibersysFirewall/dbm/
              usuario: /CibersysFirewall/dbm/usuario
              countries: /CibersysFirewall/dbm/countries
              path: CibersysFirewall/dbm/
              route: http://localhost:5656
            mannager:
              services: /CibersysFirewall/mannager/
              usuario: /CibersysFirewall/mannager/usuario
              update: /CibersysFirewall/mannager/update
              recuperatepassword: /CibersysFirewall/mannager/recuperatepassword
              passwordchange: /CibersysFirewall/mannager/passwordchange
              setUsuario: /CibersysFirewall/mannager/setUsuario
              users: /CibersysFirewall/mannager/users
              setCliente: /CibersysFirewall/mannager/setCliente
              clients: /CibersysFirewall/mannager/clients
              countries : /CibersysFirewall/mannager/countries
              path: CibersysFirewall/mannager/
              route: http://localhost:5657
            group:
              services: /CibersysFirewall/group/
              group: /CibersysFirewall/group/group
              path: CibersysFirewall/group/
              route: http://localhost:5659
  #Configuracion de seguridad
    token:
      header: X-Auth-Token
      secret: 1234567890*-+/AbCdEfGhIjKlMnOpQrStUvWxYz.,
      expiration: 604800


---
spring:
  profiles: production
cibersys:
  services:
            login: /CibersysFirewall/public/login
            update: /CibersysFirewall/public/update
            passwordchange: /CibersysFirewall/public/passwordchange
            services:
              public: /CibersysFirewall/public/
              private: /CibersysFirewall/private/
            path: CibersysFirewall/

            dbm:
              services: /CibersysFirewall/dbm/
              usuario: /CibersysFirewall/dbm/usuario
              path: CibersysFirewall/dbm/
              route: http://localhost:5656
            mannager:
              services: /CibersysFirewall/mannager/
              usuario: /CibersysFirewall/mannager/usuario
              update: /CibersysFirewall/mannager/update
              recuperatepassword: /CibersysFirewall/mannager/recuperatepassword

              path: CibersysFirewall/mannager/
              route: http://localhost:5657

server:
  ssl:
      key-store: /etc/letsencrypt/live/qa.cc.cloudvoice.io/keystore.p12
      keyStoreType: PKCS12
      key-store-password: ark123456
  security:
      require-ssl: true

---
spring:
  profiles: development
cibersys:
  services:
        dbm:
          route: http://localhost:5656
        mannager:
          route: http://localhost:5657

---
spring:
  profiles: remote
cibersys:
  services:
        dbm:
          route: http://localhost:5656
        mannager:
          route: http://localhost:5657