server:
  port: 5657

#Configuracion de seguridad
cibersys:
  token:
    header: X-Auth-Token
    secret: 1234567890*-+/AbCdEfGhIjKlMnOpQrStUvWxYz.,
    expiration: 604800

  #Configuracion de enrutamiento
  services:
          login: /CibersysFirewall/login/
          services: /CibersysFirewall/mannager/
          path: CibersysFirewall/mannager/

          dbm:
            services: /CibersysFirewall/dbm/
            usuario: /CibersysFirewall/dbm/usuario
            update: /CibersysFirewall/dbm/update
            recuperatepassword: /CibersysFirewall/dbm/recuperatepassword
            passwordchange: /CibersysFirewall/dbm/passwordchange
            setUsuario: /CibersysFirewall/dbm/setUsuario
            setCliente: /CibersysFirewall/dbm/setCliente
            path: CibersysFirewall/dbm/
            route: http://localhost:5656

          mannager:
            services: /CibersysFirewall/mannager/
            usuario: /CibersysFirewall/mannager/usuario
            path: CibersysFirewall/mannager/
            update: /CibersysFirewall/mannager/update
            passwordchange: /CibersysFirewall/mannager/passwordchange
            route: http://localhost:5657

          mailer:
            path: CibersysFirewall/mailer/
            route: http://localhost:5658
            services: CibersysFirewall/mailer/
            recuperatepassword: /CibersysFirewall/mailer/recuperatepassword
            setUsuario: /CibersysFirewall/mailer/setUsuario
            update: /CibersysFirewall/mailer/update

---
spring:
  application:
    name: accounts-mannager
  profiles: production
cibersys:
  services:
          dbm:
            services: /CibersysFirewall/dbm/
            usuario: /CibersysFirewall/dbm/usuario
            update: /CibersysFirewall/dbm/update
            recuperatepassword: /CibersysFirewall/dbm/recuperatepassword
            passwordchange: /CibersysFirewall/dbm/passwordchange
            path: CibersysFirewall/dbm/
            route: http://localhost:5656

          mannager:
            services: /CibersysFirewall/mannager/
            usuario: /CibersysFirewall/mannager/usuario
            path: CibersysFirewall/mannager/
            update: /CibersysFirewall/mannager/update
            route: https://localhost:5657

          mailer:
            path: CibersysFirewall/mailer/
            route: http://localhost:5658
            services: CibersysFirewall/mailer/
            recuperatepassword: /CibersysFirewall/mailer/recuperatepassword
            update: /CibersysFirewall/mailer/update
     

---
spring:
  profiles: development
  datasource:
cibersys:
  services:
        dbm:
          route: http://localhost:5656

---
spring:
  profiles: remote
  datasource:
cibersys:
  services:
        dbm:
          route: http://localhost:5656




